groups:
  - name: demo-alerts
    rules:
      - alert: InstanceDown
        expr: up == 0
        for: 10s
        labels:
          severity: critical
        annotations:
          summary: 'Instance {{ $labels.instance }} is down'
          description: 'Job {{ $labels.job }} on {{ $labels.instance }} is unreachable for more than 10s.'
