# vars/main.yml
prometheus_version: "2.52.0"
prometheus_user: prometheus
prometheus_group: prometheus
prometheus_install_dir: /usr/local/bin
prometheus_config_dir: /etc/prometheus
prometheus_data_dir: /var/lib/prometheus
prometheus_service_path: /etc/systemd/system/prometheus.service
prometheus_port: 9090
