---
- name: restart prometheus
  ansible.builtin.systemd:
    name: prometheus
    state: restarted
    enabled: yes

- name: restart alertmanager
  ansible.builtin.service:
    name: alertmanager
    state: restarted
    enabled: yes

    
